export const articles = [
  { slug: "five-minute-morning-reset", category: "Lifestyle", title: "A five-minute morning reset for steadier energy", excerpt: "Small, repeatable choices can make your day feel more balanced before it begins.", date: "Today", readTime: "4 min read", emoji: "☀️", color: "from-amber-100 to-orange-100", body: ["A healthy routine does not need to begin with a complete overhaul. One glass of water, a few minutes of daylight, and a moment away from notifications can give your day a calmer starting point.", "Choose one habit that feels easy enough to do even on a busy day. Consistency matters more than intensity. If you have a medical condition or specific health goal, ask your doctor which routine is right for you."] },
  { slug: "understanding-your-prescription", category: "Medicine", title: "Understanding your prescription: questions worth asking", excerpt: "A simple checklist helps you use medicines safely and confidently.", date: "Yesterday", readTime: "5 min read", emoji: "💊", color: "from-teal-100 to-cyan-100", body: ["Before leaving a pharmacy, make sure you understand what the medicine is for, when to take it, and whether food or other medicines could affect it.", "Never change a prescribed dose without speaking to a qualified clinician. Your pharmacist is also a useful source of practical, medication-specific guidance."] },
  { slug: "walking-for-heart-health", category: "Lifestyle", title: "How a regular walk supports heart health", excerpt: "Movement can be approachable, social, and beneficial at the same time.", date: "2 days ago", readTime: "3 min read", emoji: "🚶", color: "from-lime-100 to-emerald-100", body: ["Walking is one of the most accessible forms of movement. Starting with a pace and duration that feels comfortable makes it easier to build a sustainable habit.", "Talk to a clinician before starting a new exercise program if you have chest pain, dizziness, or an existing heart condition."] },
  { slug: "reading-health-headlines", category: "Research", title: "How to read health headlines with a critical eye", excerpt: "A single study rarely provides the whole answer. Here is what to look for.", date: "3 days ago", readTime: "6 min read", emoji: "🔬", color: "from-indigo-100 to-violet-100", body: ["Health research is valuable, but a headline may simplify what a study actually found. Look for the study size, who participated, and whether the finding is an early result or established guidance.", "Use trusted health organisations and your own care team to put new research in context. This page is educational and is not medical advice."] },
];

export const dailyBrief = [
  { title: "Lifestyle focus", text: "Aim for a consistent sleep and wake time this week.", emoji: "🌙" },
  { title: "Research lens", text: "Check the source before sharing a health claim.", emoji: "🔎" },
  { title: "Medicine reminder", text: "Keep an updated list of your medications and doses.", emoji: "📋" },
];
